# Generated by Django 5.2.7 on 2025-10-20 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("compliance", "0001_initial"),
        ("core", "0001_initial"),
        ("governance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancechecklist",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.profile",
            ),
        ),
        migrations.AddField(
            model_name="compliancerequirement",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compliance_owned",
                to="core.profile",
            ),
        ),
        migrations.AddField(
            model_name="predictivealert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.profile",
            ),
        ),
        migrations.AddField(
            model_name="regulationmapping",
            name="mapped_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.profile",
            ),
        ),
        migrations.AddField(
            model_name="regulationmapping",
            name="policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="governance.policy",
            ),
        ),
        migrations.AddField(
            model_name="regulationmapping",
            name="requirement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="compliance.compliancerequirement",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="regulationmapping",
            unique_together={("policy", "requirement")},
        ),
    ]
