"""
Django settings for grc_pfa project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$@gyny0z%*@=2n1h5um(bmjei4w^)wvdd+ol+88fiol0&jsfk1"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # ... Django defaults ...
    'django.contrib.sites',  # Often useful for multi-app/domain setup
    'django_extensions',     # Useful for management commands
    
    # Third-Party Apps
    'rest_framework',
    'corsheaders',

    # Local Apps
    'core',
    'governance',
    'risk',
    'compliance',
    'audit',
]

# Configure CORS (required for your React frontend)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080", # Assuming your Vite dev server uses this port (as in vite.config.ts)
]
CORS_ALLOW_CREDENTIALS = True



MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "grc_pfa.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "grc_pfa.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
    #"default": {
        #"ENGINE": "django.db.backends.sqlite3",
        #"NAME": BASE_DIR / "db.sqlite3",
    #}
#}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'grc_db',       # Your PostgreSQL database name
        'USER': 'dimeji',       # Your PostgreSQL user
        'PASSWORD': 'Labake2025', # Your PostgreSQL password
        'HOST': 'localhost',      # Or your database host/IP
        'PORT': '5432',
    }
}

# NEO4J CONFIGURATION (Hybrid Persistence Model)
NEOMODEL_NEO4J_BOLT_URL = 'bolt://neo4j:password@localhost:7687'  # <-- UPDATE THIS
NEOMODEL_MAX_CONNECTION_LIFETIME = 3600
NEOMODEL_ENCRYPTED = False

# Initialize neomodel config to connect
try:
    from neomodel import config as neomodel_config
    neomodel_config.DATABASE_URL = NEOMODEL_NEO4J_BOLT_URL
except ImportError:
    pass


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
