# Generated by Django 5.2.7 on 2025-10-20 02:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("governance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recommendation_type", models.CharField(max_length=255)),
                ("entity_type", models.CharField(max_length=100)),
                ("entity_id", models.UUIDField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("rationale", models.TextField()),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("priority", models.CharField(default="medium", max_length=50)),
                ("status", models.CharField(default="pending", max_length=50)),
                ("implemented_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "implemented_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("severity", models.CharField(max_length=50)),
                ("status", models.CharField(default="reported", max_length=50)),
                ("root_cause", models.TextField(blank=True, null=True)),
                ("corrective_action", models.TextField(blank=True, null=True)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_assigned",
                        to="core.profile",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_reported",
                        to="core.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("category", models.CharField(max_length=100)),
                ("likelihood", models.IntegerField()),
                ("impact", models.IntegerField()),
                ("status", models.CharField(default="open", max_length=50)),
                ("mitigation_plan", models.TextField(blank=True, null=True)),
                ("approval_status", models.CharField(default="pending", max_length=50)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risks_approved",
                        to="core.profile",
                    ),
                ),
                (
                    "objective",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="governance.corporateobjective",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risks_owned",
                        to="core.profile",
                    ),
                ),
                (
                    "risk_champion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risks_championed",
                        to="core.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskFactor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("factor_name", models.CharField(max_length=255)),
                ("factor_value", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="risk.risk"
                    ),
                ),
            ],
        ),
    ]
